services:
  - type: web
    name: quickshop-ug
    runtime: docker
    plan: free
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_TIMEZONE
        value: Africa/Kampala
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: BASE_URL
        sync: false
